[package]
name = "wav-wav"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
iced = "0.13.1"
rfd = "0.15.3"
rodio = "0.20.1"
slint = "1.10.0"

[build-dependencies]
slint-build = "1.10.0"
