import { Button, VerticalBox, TextEdit, SpinBox, CheckBox, Slider, HorizontalBox } from "std-widgets.slint";

import "./res/fonts/Neucha-Regular.ttf";
import "./res/fonts/RubikMoonrocks-Regular.ttf";
import "./res/fonts/IrishGrover-Regular.ttf";

import { MyButton } from "./my-button.slint";
import { Player } from "player.slint";
import { Settings } from "settings.slint";
import { TopLine } from "top-line.slint";

export component AppWindow inherits Window {
    default-font-family: "Neucha";
    default-font-size: 24px;

    callback choose_audio_file <=> input_player.choose_file_button_clicked;
    callback input_play_toggle <=> input_player.play_button_clicked;
    callback input_seek <=> input_player.seek_audio;
    in-out property <float> input_playback_position: 0.0;

    max-width: 1440px;
    max-height: 1024px;
    min-width: 720px;
    min-height: 512px;

    Image {
        source: @image-url("res/background.png");
        image-fit: cover;
        width: parent.width;
        height: parent.height;
    }
    // in-out property <int> counter: 42;
    // callback request-increase-value();


    VerticalLayout {
        padding: 0px;

        TopLine {
            x: 0;
            width: parent.width;
        }

        VerticalLayout {

            input_player := Player {
                filename: "filename.wav";
                playback_position <=> root.input_playback_position;
            }

            Settings {
                check-box-text: "Скрыть повторения";
                button-text: "Расшифровать";
            }

            Rectangle {

                TextInput {
                    min-height: 100px;
                    text: "Result is here";
                }

                background: black.transparentize(0.5);
            }

            Settings {
                check-box-text: "Делать повторения";
                button-text: "Зашифровать";
            }

            Player {
                filename: "filename.wav";
            }
        }
    }
}
