import {HorizontalBox} from "std-widgets.slint";
import {MyButton} from "./my-button.slint"; 

export component BitSelector inherits Rectangle {

    in-out property <int> minimum: 1;
    in-out property <int> maximum: 8;
    in-out property <int> value: 1;

    property <length> button-size: 30px;

    border-radius: 8px;
    background: black;

    HorizontalBox {
        // alignment: center;

        MyButton {
            width: root.button-size;
            height: root.button-size;
            text: "<";
            text-color: black;
            background: self.pressed ? gray : white;

            clicked => {
                root.value = Math.max(root.value - 1, root.minimum);
            }
        }

        Rectangle {
            Text {
                text: root.value + " бит";
                color: white;
            }
        }

        MyButton {
            width: root.button-size;
            height: root.button-size;
            text: ">";
            text-color: black;
            background: self.pressed ? gray : white;
            clicked => {
                root.value = Math.min(root.value + 1, root.maximum);
            }
        }
    }
}
