import {HorizontalBox} from "std-widgets.slint";
import {MyButton} from "./my-button.slint"; 

export component MyCheckBox inherits Rectangle {

    in-out property <bool> value: true;
    in-out property text <=> t.text;

    border-radius: 8px;
    background: black;
    min-width: box.min-width;

    box := HorizontalBox {
        alignment: center;

        button := MyButton {
            width: 30px;
            height: 30px;
            text: root.value ? "x" : " ";
            text-color: black;
            background: touch-area.pressed ? gray : white;

            // clicked => {
            //     root.checked = !root.checked;
            // }
        }

        Rectangle {
            t := Text {
                color: white;
            }
        }
    }

    touch-area := TouchArea {
        clicked => {
            root.value = !root.value;
        }
    }
}
