import { Button, VerticalBox, TextEdit, SpinBox, CheckBox, Slider, HorizontalBox } from "std-widgets.slint";
import {MyButton} from "./my-button.slint"; 
import {BitSelector} from "./bit-selector.slint"; 
import {MyCheckBox} from "./my-checkbox.slint";

export component Settings inherits Rectangle {

    callback button-clicked <=> button.clicked;
    in-out property <string> check-box-text <=> check-box.text;
    in-out property <string> button-text <=> button.text;
    out property bits <=> bit-selector.value;
    out property repeating <=> check-box.value;

    HorizontalLayout {
        padding: 0px;
        min-height: 15px;

        alignment: space-between;

        Rectangle {
            min-width: 200px;
            width: 30%;
            background: #0005;

            check-box := MyCheckBox {
                value: true;
                background: black.transparentize(30%);
            }
        }

        bit-selector := BitSelector {
            width: 30%;
            // background: #0005;
            minimum: 1;
            maximum: 8;
            value: 1;
            background: black.transparentize(30%);
        }

        button := MyButton {
            width: 30%;
            background: (self.pressed ? gray : black).transparentize(30%);
            clicked => {
                debug("Расшифровать");
            }
        }
    }
}
