import { Button, VerticalBox, TextEdit, SpinBox, CheckBox, Slider, HorizontalBox } from "std-widgets.slint";
import {MyButton} from "./my-button.slint"; 
import {BitSelector} from "./bit-selector.slint"; 
import {MyCheckBox} from "./my-checkbox.slint";

export component Settings inherits Rectangle {

    in property <string> check-box-text: "Повторения";
    in property <string> button-text: "Запустить";

    HorizontalBox {
        min-height: 15px;

        alignment: space-around;

        Rectangle {
            min-width: 200px;
            width: 30%;
            background: #0005;

            MyCheckBox {
                text: root.check-box-text;
                background: black.transparentize(30%);
            }
        }

        BitSelector {
            width: 30%;
            // background: #0005;
            minimum: 1;
            maximum: 8;
            value: 1;
            background: black.transparentize(30%);
        }

        MyButton {
            width: 30%;
            text: root.button-text;
            background: (self.pressed ? gray : black).transparentize(30%);
            clicked => {
                debug("Расшифровать");
            }
        }
    }
}
